obstacle_range: 1.5
raytrace_range: 2.5
footprint: [[0.1, 0.17], [0.1, -0.17], [-0.25, -0.17], [-0.25, 0.17]]
inflation_radius: 1.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
